<!-- wp:snow-monkey-blocks/section {"contentsAlignment":"right","className":"RJE_R002LP_message_normal is-style-RJE_R002LP_message_normal"} -->
<div class="wp-block-snow-monkey-blocks-section smb-section smb-section--right smb-section--fit RJE_R002LP_message_normal is-style-RJE_R002LP_message_normal"><div class="smb-section__inner"><div class="c-container"><div class="smb-section__subtitle"><meta charset="utf-8">CONSEPT</div><h2 class="smb-section__title"><meta charset="utf-8">髪質に悩む全ての人へ。<br>あなたに最適なシャンプーが<br>必ず見つかる。</h2><div class="smb-section__body"><!-- wp:snow-monkey-blocks/section-break-the-grid {"imageID":701,"imageMediaType":"image","imagePosition":"left","imageSizeSlug":"full","verticalAlignment":"top","contentSize":"m","contentHorizontalPosition":"","contentVerticalPosition":"","mobileOrder":"image","contentsAlignment":"left"} -->
<div class="wp-block-snow-monkey-blocks-section-break-the-grid smb-section smb-section-break-the-grid smb-section-break-the-grid--left smb-section-break-the-grid--mobile-image smb-section--left"><div class="smb-section__inner"><div class="c-container"><div class="c-row c-row--margin c-row--lg-top"><div class="c-row__col c-row__col--1-1 c-row__col--lg-1-2"><div class="smb-section-break-the-grid__content smb-section-break-the-grid__content--w-m"><h2 class="smb-section__title smb-section-break-the-grid__title">あなたの髪の悩みを聞かせて下さい。</h2><div class="smb-section__body smb-section-break-the-grid__body"><!-- wp:paragraph -->
<p>生まれつきの髪のくせでずっと悩んできた人。<br>カラーやパーマを繰り返してきた結果、髪のダメージが気になり始めた人。<br>髪の悩みはそれぞれ違います。<br>自分の髪にあったシャンプーを探そうと思っても、何から考えて探せば良いかわからない。<br>そんなお悩みから生まれたのが、MATCHです。<br>髪質の診断から、あなたに合ったシャンプーをお届けします。</p>
<!-- /wp:paragraph -->

<!-- wp:snow-monkey-blocks/buttons {"contentJustification":"right"} -->
<div class="wp-block-snow-monkey-blocks-buttons smb-buttons is-content-justification-right"><!-- wp:snow-monkey-blocks/btn {"className":"is-style-text"} -->
<div class="wp-block-snow-monkey-blocks-btn smb-btn-wrapper is-style-text"><a class="smb-btn" href=""><span class="smb-btn__label">View More</span></a></div>
<!-- /wp:snow-monkey-blocks/btn --></div>
<!-- /wp:snow-monkey-blocks/buttons --></div></div></div><div class="c-row__col c-row__col--1-1 c-row__col--lg-1-2"><div class="smb-section-break-the-grid__figure smb-section-break-the-grid__figure--w-l"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/photo-fruits2.jpg" alt="" width="1200" height="818" class="wp-image-701"/></div></div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/section-break-the-grid --></div></div></div></div>
<!-- /wp:snow-monkey-blocks/section -->