<!-- wp:snow-monkey-blocks/section {"fixedBackgroundColor":"#f4f4f4","align":"full","className":"RJE_R002LP_variation is-style-RJE_R002LP_section1"} -->
<div class="wp-block-snow-monkey-blocks-section alignfull smb-section smb-section--fit RJE_R002LP_variation is-style-RJE_R002LP_section1"><div class="smb-section__fixed-background" style="padding-top:0;padding-bottom:0;background-color:#f4f4f4"></div><div class="smb-section__inner"><div class="c-container"><div class="smb-section__contents-wrapper"><div class="smb-section__header"><div class="smb-section__subtitle"><meta charset="utf-8">SHAMPOO LIST</div><h2 class="smb-section__title"><meta charset="utf-8">MATCHのシャンプー</h2><div class="smb-section__lede-wrapper"><div class="smb-section__lede"><meta charset="utf-8">MATCHのシャンプーから、人気のものを少しだけ紹介します。<br>どんな人でも必ずお気に入りのシャンプーが見つかるように、ここにある以外にも、MATCHはたくさんのシャンプーをご用意しています。</div></div></div><div class="smb-section__body"><!-- wp:snow-monkey-blocks/items {"md":2,"lg":3,"className":"is-style-RJE_R002LP_variation_items"} -->
<div class="wp-block-snow-monkey-blocks-items smb-items is-style-RJE_R002LP_variation_items"><div class="c-row c-row--margin" data-columns="1" data-md-columns="2" data-lg-columns="3"><!-- wp:snow-monkey-blocks/items-item-standard {"imageID":761} -->
<div class="wp-block-snow-monkey-blocks-items-item-standard c-row__col"><div class="smb-items__item"><div class="smb-items__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/photo-teatime2.jpg" alt="" width="640" height="480" class="wp-image-761"/></div><div class="smb-items__item__body"><div class="smb-items__item__title">Melting Chocolate</div><div class="smb-items__item__lede">商品コード : 1001</div><div class="smb-items__item__content">しっとりとした、艶やかな髪に整えるシャンプー。甘い香りがバスタイムを包みます。</div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-item-standard -->

<!-- wp:snow-monkey-blocks/items-item-standard {"imageID":757} -->
<div class="wp-block-snow-monkey-blocks-items-item-standard c-row__col"><div class="smb-items__item"><div class="smb-items__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/photo-fruits.jpg" alt="" width="640" height="480" class="wp-image-757"/></div><div class="smb-items__item__body"><div class="smb-items__item__title">Mid-Summer Orange</div><div class="smb-items__item__lede">商品コード : 3012</div><div class="smb-items__item__content">頭皮の油分と水分のバランスを整えて、サラサラな髪をキープするシャンプー。柑橘系で爽やかな香りです。</div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-item-standard -->

<!-- wp:snow-monkey-blocks/items-item-standard {"imageID":759} -->
<div class="wp-block-snow-monkey-blocks-items-item-standard c-row__col"><div class="smb-items__item"><div class="smb-items__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/photo-green5.jpg" alt="" width="640" height="480" class="wp-image-759"/></div><div class="smb-items__item__body"><div class="smb-items__item__title">Herb Garden</div><div class="smb-items__item__lede">商品コード : 4006</div><div class="smb-items__item__content">ダメージが気になる髪を、修復しながらまとまりのある髪質に導くシャンプー。ローズマリーが香ります。</div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-item-standard -->

<!-- wp:snow-monkey-blocks/items-item-standard {"imageID":760} -->
<div class="wp-block-snow-monkey-blocks-items-item-standard c-row__col"><div class="smb-items__item"><div class="smb-items__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/photo-teatime.jpg" alt="" width="640" height="480" class="wp-image-760"/></div><div class="smb-items__item__body"><div class="smb-items__item__title">Afternoon Tea</div><div class="smb-items__item__lede">商品コード : 4017</div><div class="smb-items__item__content">癖のある髪を落ち着かせて、しなやかな髪に整えるシャンプー。紅茶の香りが洗い流した後も続きます。</div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-item-standard -->

<!-- wp:snow-monkey-blocks/items-item-standard {"imageID":758} -->
<div class="wp-block-snow-monkey-blocks-items-item-standard c-row__col"><div class="smb-items__item"><div class="smb-items__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/photo-green4.jpg" alt="" width="640" height="480" class="wp-image-758"/></div><div class="smb-items__item__body"><div class="smb-items__item__title">Baby’s Breath</div><div class="smb-items__item__lede">商品コード : 5003</div><div class="smb-items__item__content">ついつい触りたくなる柔らかい髪質を実現するシャンプー。フローラルブーケの、甘くて可憐な香りです。</div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-item-standard -->

<!-- wp:snow-monkey-blocks/items-item-standard {"imageID":756} -->
<div class="wp-block-snow-monkey-blocks-items-item-standard c-row__col"><div class="smb-items__item"><div class="smb-items__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/photo-fireworks.jpg" alt="" width="640" height="480" class="wp-image-756"/></div><div class="smb-items__item__body"><div class="smb-items__item__title">Party Dress</div><div class="smb-items__item__lede">商品コード : 5011</div><div class="smb-items__item__content">髪にハリとボリュームを出してくれるシャンプー。香りも華やかで、楽しいお出かけを後押しします。</div></div></div></div>
<!-- /wp:snow-monkey-blocks/items-item-standard --></div></div>
<!-- /wp:snow-monkey-blocks/items --></div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/section -->