<!-- wp:snow-monkey-blocks/section {"contentsAlignment":"left","fixedBackgroundColor":"#f4f4f4","align":"full","className":"RJE_R002LP_merit is-style-RJE_R002LP_section1"} -->
<div class="wp-block-snow-monkey-blocks-section alignfull smb-section smb-section--left smb-section--fit RJE_R002LP_merit is-style-RJE_R002LP_section1"><div class="smb-section__fixed-background" style="padding-top:0;padding-bottom:0;background-color:#f4f4f4"></div><div class="smb-section__inner"><div class="c-container"><div class="smb-section__contents-wrapper smb-section__contents-wrapper--left"><div class="smb-section__header"><div class="smb-section__subtitle"><meta charset="utf-8">FEATURE</div><h2 class="smb-section__title"><meta charset="utf-8">MATCHの特徴</h2></div><div class="smb-section__body"><!-- wp:snow-monkey-blocks/panels {"md":2,"lg":3,"className":"is-style-RJE_R002LP_merit_panels"} -->
<div class="wp-block-snow-monkey-blocks-panels smb-panels is-style-RJE_R002LP_merit_panels" data-image-padding="false"><div class="c-row c-row--margin c-row--fill" data-columns="1" data-md-columns="2" data-lg-columns="3"><!-- wp:snow-monkey-blocks/panels-item {"imageID":290,"imageSizeSlug":"thumbnail"} -->
<div class="wp-block-snow-monkey-blocks-panels-item c-row__col"><div class="smb-panels__item"><div class="smb-panels__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/illust1.png" alt="" width="54" height="95" class="wp-image-290"/></div><div class="smb-panels__item__body"><div class="smb-panels__item__title">診断やフィードバックで<br>髪質と好みを把握</div><div class="smb-panels__item__content">質問に答えたり、使用したシャンプーのフィードバックで、あなたの髪について教えてください</div></div></div></div>
<!-- /wp:snow-monkey-blocks/panels-item -->

<!-- wp:snow-monkey-blocks/panels-item {"imageID":291,"imageSizeSlug":"thumbnail"} -->
<div class="wp-block-snow-monkey-blocks-panels-item c-row__col"><div class="smb-panels__item"><div class="smb-panels__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/illust2.png" alt="" width="92" height="90" class="wp-image-291"/></div><div class="smb-panels__item__body"><div class="smb-panels__item__title">幅広いラインナップから<br>あなたのベストを提案</div><div class="smb-panels__item__content">MATCHのシャンプーは種類が豊富。あなたの髪にぴったりのシャンプーを提案します</div></div></div></div>
<!-- /wp:snow-monkey-blocks/panels-item -->

<!-- wp:snow-monkey-blocks/panels-item {"imageID":292,"imageSizeSlug":"thumbnail"} -->
<div class="wp-block-snow-monkey-blocks-panels-item c-row__col"><div class="smb-panels__item"><div class="smb-panels__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/illust3.png" alt="" width="69" height="89" class="wp-image-292"/></div><div class="smb-panels__item__body"><div class="smb-panels__item__title">定期的な継続購入が<br>リーズナブル</div><div class="smb-panels__item__content">継続購入がお得。フィードバックを繰り返すことで、あなたの好みのシャンプーに近づきます</div></div></div></div>
<!-- /wp:snow-monkey-blocks/panels-item --></div></div>
<!-- /wp:snow-monkey-blocks/panels --></div></div></div></div></div>
<!-- /wp:snow-monkey-blocks/section -->